let data = [
  {
    id: "1",
    name: "[BEST]_Hasta pants_7 Colors",
    brand: "프라크티",
    url: "https://product.29cm.co.kr/catalog/3005272?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/1.webp",
    discount: "30%",
    price: "46,900",
    badges: ["쿠폰"],
    likes: 2252,
    rating: {
      score: 4.9,
      count: 314,
    },
  },
  {
    id: "2",
    name: "브라패드",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/1636482?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/2.webp",
    discount: "30%",
    price: "2,100",
    badges: ["쿠폰"],
    likes: 396,
    rating: {
      score: 4.7,
      count: 236,
    },
  },
  {
    id: "3",
    name: "[29CM 단독]_OZPN2030 스모킹 팬츠 - 27 colors",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/1447964?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/3.webp",
    discount: "30%",
    price: "40,600",
    badges: ["쿠폰", "여름맞이"],
    likes: 3636,
    rating: {
      score: 5.0,
      count: 488,
    },
  },
  {
    id: "4",
    name: "여성 요가복 DEVI-B0013-블랙 필라테스 군살제로 바이커 5부",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/347673?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/4.webp",
    discount: "41%",
    price: "13,685",
    badges: ["쿠폰", "여름맞이"],
    likes: 5073,
    rating: {
      score: 4.5,
      count: 1206,
    },
  },
  {
    id: "5",
    name: "여성 요가복 DEVI-TS0011-화이트 필라테스 도로시 크롭탑",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1589780?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/5.webp",
    discount: "44%",
    price: "19,040",
    badges: ["쿠폰", "여름맞이"],
    likes: 3021,
    rating: {
      score: 4.7,
      count: 406,
    },
  },
  {
    id: "6",
    name: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1589722?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/6.webp",
    discount: "44%",
    price: "19,040",
    badges: ["쿠폰", "여름맞이"],
    likes: 1185,
    rating: {
      score: 4.5,
      count: 189,
    },
  },
  {
    id: "7",
    name: "[25SS]_Nirlamba pants_3 Colors",
    brand: "프라크티",
    url: "https://product.29cm.co.kr/catalog/3087069?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/7.webp",
    discount: "30%",
    price: "48,300",
    badges: ["쿠폰"],
    likes: 367,
    rating: {
      score: 5.0,
      count: 48,
    },
  },
  {
    id: "8",
    name: "파인 스트링 윈드자켓 DEVI-O0019-화이트",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3063206?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/8.webp",
    discount: "10%",
    price: "31,500",
    badges: ["여름맞이"],
    likes: 742,
    rating: {
      score: 4.5,
      count: 13,
    },
  },
  {
    id: "9",
    name: "모어아웃 여성운동복 요가복 원마일웨어 애슬레져룩 바스락팬츠 에어 썸머 조거 밴딩 팬츠 5PP911",
    brand: "모어아웃",
    url: "https://product.29cm.co.kr/catalog/1291701?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/9.webp",
    discount: "50%",
    price: "22,015",
    badges: ["쿠폰", "여름맞이"],
    likes: 3387,
    rating: {
      score: 4.5,
      count: 383,
    },
  },
  {
    id: "10",
    name: "[29CM 단독]_모어아웃 여성요가복 핀턱 쭈리 벌룬 팬츠 5PP3533",
    brand: "모어아웃",
    url: "https://product.29cm.co.kr/catalog/2028023?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/10.webp",
    discount: "53%",
    price: "27,370",
    badges: ["쿠폰", "여름맞이"],
    likes: 362,
    rating: {
      score: 5.0,
      count: 18,
    },
  },
  {
    id: "11",
    name: "여성 요가복 DEVI-TS0024-에쉬그레이 필라테스 엣지크롭 슬리브리스 나시",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1105498?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/11.webp",
    discount: "41%",
    price: "17,255",
    badges: ["쿠폰", "여름맞이"],
    likes: 1182,
    rating: {
      score: 4.5,
      count: 128,
    },
  },
  {
    id: "12",
    name: "모어아웃 여성요가복 코튼 크롭 숏 슬리브 티셔츠 4TT5454",
    brand: "모어아웃",
    url: "https://product.29cm.co.kr/catalog/3152167?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/12.webp",
    discount: "53%",
    price: "15,470",
    badges: ["쿠폰", "여름맞이"],
    likes: 40,
    rating: {
      score: 5.0,
      count: 1,
    },
  },
  {
    id: "13",
    name: "여성 요가복 DEVI-TS0033-브라운 필라테스 리비아 브라탑",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3113652?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/13.webp",
    discount: "30%",
    price: "19,600",
    badges: ["쿠폰", "여름맞이"],
    likes: 52,
    rating: {
      score: 4.0,
      count: 6,
    },
  },
  {
    id: "14",
    name: "[25SS]_Yoga family T-shirt_2 Colors",
    brand: "프라크티",
    url: "https://product.29cm.co.kr/catalog/3078492?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/14.webp",
    discount: "30%",
    price: "32,200",
    badges: ["쿠폰"],
    likes: 558,
    rating: {
      score: 5.0,
      count: 32,
    },
  },
  {
    id: "15",
    name: "[BEST]_Raja bra top_6 Colors",
    brand: "프라크티",
    url: "https://product.29cm.co.kr/catalog/3014005?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/15.webp",
    discount: "30%",
    price: "28,700",
    badges: ["쿠폰"],
    likes: 285,
    rating: {
      score: 4.5,
      count: 85,
    },
  },
  {
    id: "16",
    name: "Mukha cover top [ grape purple ]",
    brand: "프라크티",
    url: "https://product.29cm.co.kr/catalog/2891905?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/16.webp",
    discount: "30%",
    price: "32,900",
    badges: ["쿠폰"],
    likes: 220,
    rating: {
      score: 5,
      count: 16,
    },
  },
  {
    id: "17",
    name: "OZTB5036 코튼 모달 핀턱 브라탑 - 인디 핑크",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/2822579?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/17.webp",
    discount: "30%",
    price: "26,600",
    badges: ["쿠폰"],
    likes: 59,
    rating: {
      score: 4,
      count: 5,
    },
  },
  {
    id: "18",
    name: "웨이븐 프릴 롱슬리브 DEVI-T0112-펌킨",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/2815580?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/18.webp",
    discount: "37%",
    price: "13,860",
    badges: ["쿠폰"],
    likes: 139,
    rating: {
      score: 4.5,
      count: 16,
    },
  },
  {
    id: "19",
    name: "여성 요가복 DEVI-B0073-블랙 필라테스 군살제로 와이드 부츠컷 레깅스",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/2365021?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/19.webp",
    discount: "41%",
    price: "19,040",
    badges: ["쿠폰"],
    likes: 2549,
    rating: {
      score: 4.5,
      count: 185,
    },
  },
  {
    id: "20",
    name: "[29CM 단독]_모어아웃 여성요가복 바스락 튤립 쇼츠 5PP3532",
    brand: "모어아웃",
    url: "https://product.29cm.co.kr/catalog/2073553?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/20.webp",
    discount: "54%",
    price: "14,875",
    badges: ["쿠폰"],
    likes: 644,
    rating: {
      score: 5,
      count: 59,
    },
  },
  {
    id: "21",
    name: "비비아나 셔링 쇼츠 DEVI-B0088-차콜",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3234166?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/21.webp",
    discount: "19%",
    price: "19,440",
    badges: ["쿠폰"],
    likes: 64,
    rating: {
      score: 0,
      count: 0,
    },
  },
  {
    id: "22",
    name: "줄리 셔링 캡 슬리브 DEVI-T0130-멜란지그레이",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3226893?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/22.webp",
    discount: "24%",
    price: "17,595",
    badges: ["쿠폰"],
    likes: 70,
    rating: {
      score: 5,
      count: 1,
    },
  },
  {
    id: "23",
    name: "익스틴 서포트 티 DEVI-T0045-베이지",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3113648?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/23.webp",
    discount: "41%",
    price: "16,065",
    badges: ["쿠폰"],
    likes: 105,
    rating: {
      score: 5,
      count: 4,
    },
  },
  {
    id: "24",
    name: "타탄 플레어 힙커버 DEVI-B0081-옐로우",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/2985758?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/24.webp",
    discount: "41%",
    price: "17,850",
    badges: ["쿠폰"],
    likes: 100,
    rating: {
      score: 5,
      count: 4,
    },
  },
  {
    id: "25",
    name: "웨이븐 프릴 롱슬리브 DEVI-T0112-블랙",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/2815577?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/25.webp",
    discount: "37%",
    price: "13,860",
    badges: ["쿠폰"],
    likes: 1320,
    rating: {
      score: 5,
      count: 121,
    },
  },
  {
    id: "26",
    name: "OZPN2112 백 슬릿 플레어 요가팬츠 - 파스텔 그린",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/2636315?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/26.webp",
    discount: "30%",
    price: "40,600",
    badges: ["쿠폰"],
    likes: 94,
    rating: {
      score: 5,
      count: 13,
    },
  },
  {
    id: "27",
    name: "OZTJ3027 코튼 요루 피그먼트 한텐 - 차콜",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/2549580?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/27.webp",
    discount: "30%",
    price: "45,500",
    badges: ["쿠폰"],
    likes: 100,
    rating: {
      score: 5,
      count: 12,
    },
  },
  {
    id: "28",
    name: "[29CM 단독]_[1&1] OZPG6005 에센셜 조거팬츠",
    brand: "오즈이즈",
    url: "https://product.29cm.co.kr/catalog/2024911?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/28.webp",
    discount: "30%",
    price: "69,300",
    badges: ["쿠폰"],
    likes: 243,
    rating: {
      score: 5,
      count: 49,
    },
  },
  {
    id: "29",
    name: "모어아웃 여성운동복 요가복 애슬레져룩 바스락팬츠 에어 썸머 하프팬츠 5PP603",
    brand: "모어아웃",
    url: "https://product.29cm.co.kr/catalog/1289721?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/29.webp",
    discount: "54%",
    price: "14,875",
    badges: ["쿠폰"],
    likes: 1154,
    rating: {
      score: 5,
      count: 75,
    },
  },
  {
    id: "30",
    name: "페이스 슬림 반팔티 DEVI-T0061-블랙",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1159099?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/30.webp",
    discount: "41%",
    price: "11,305",
    badges: ["쿠폰", "여름맞이"],
    likes: 2627,
    rating: {
      score: 4.5,
      count: 323,
    },
  },
  {
    id: "31",
    name: "여성 요가복 DEVI-B0046-블랙 필라테스 군살제로 바이커 4부",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1126643?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/31.webp",
    discount: "32%",
    price: "15,640",
    badges: ["쿠폰", "여름맞이"],
    likes: 295,
    rating: {
      score: 4.5,
      count: 60,
    },
  },
  {
    id: "32",
    name: "여성 요가복 DEVI-TS0024-화이트 필라테스 엣지크롭 슬리브리스",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1105502?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/32.webp",
    discount: "41%",
    price: "17,255",
    badges: ["쿠폰", "여름맞이"],
    likes: 1075,
    rating: {
      score: 4.5,
      count: 264,
    },
  },
  {
    id: "33",
    name: "익스틴 서포트 티 DEVI-T0045-블랙",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1065306?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/33.webp",
    discount: "41%",
    price: "16,065",
    badges: ["여름맞이", "쿠폰"],
    likes: 1253,
    rating: {
      score: 4.5,
      count: 107,
    },
  },
  {
    id: "34",
    name: "뉴웨이브 홀릭크롭 DEVI-T0018-블랙",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/1007461?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/34.webp",
    discount: "34%",
    price: "11,305",
    badges: ["여름맞이", "쿠폰"],
    likes: 242,
    rating: {
      score: 4.5,
      count: 41,
    },
  },
  {
    id: "35",
    name: "비비아나 셔링 쇼츠 DEVI-B0088-네이비",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3234173?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/35.webp",
    discount: "19%",
    price: "19,440",
    badges: ["여름맞이", "쿠폰"],
    likes: 58,
    rating: {
      score: 0,
      count: 0,
    },
  },
  {
    id: "36",
    name: "메이 스퀘어넥 슬리브리스 DEVI-TS0051-블랙",
    brand: "데비웨어",
    url: "https://product.29cm.co.kr/catalog/3211270?product_sort=best&id=12148&source=collection",
    image: "img/collection_product/36.webp",
    discount: "36%",
    price: "17,212",
    badges: ["여름맞이", "쿠폰"],
    likes: 24,
    rating: {
      score: 0,
      count: 0,
    },
  },
];

export default data;
