let data = [
  {
    id: "b1",
    url: "/collection",
    imgUrl: "img/main_right/banner1.webp",
    alt: "banner1",
  },
  {
    id: "b2",
    url: "/collection",
    imgUrl: "img/main_right/banner2.webp",
    alt: "banner2",
  },
  {
    id: "c1",
    type: "product",
    collection: {
      title: "산지와 사람을 잇는 커피",
      description:
        "프릳츠 커피는 산지의 농부를 직접 만납니다.  중미와 인도의 커피 농장을 방문하며 생산자들과 교류하고 아름다운 품질의 생두를 얻어 커피를 만듭니다.",
      image: "img/main_right/p3.webp",
      url: "https://content.29cm.co.kr/brand-news/10972",
    },
    products: [
      {
        id: "p11",
        brand: "프릳츠",
        name: "프릳츠 디카페인",
        image: "img/main_right/p3-1.webp",
        url: "https://product.29cm.co.kr/catalog/2108591",
        price: "15,200",
        discount: "5%",
        likes: "350",
      },
      {
        id: "p12",
        brand: "프릳츠",
        name: "프릳츠 올드독",
        image: "img/main_right/p3-2.webp",
        url: "https://product.29cm.co.kr/catalog/92170",
        price: "15,200",
        discount: "5%",
        likes: "1K",
      },
    ],
  },
  {
    id: "c2",
    type: "product",
    collection: {
      url: "https://content.29cm.co.kr/brand-news/29244",
      image: "img/main_right/p4.webp",
      title: "커피 한 잔의 문학",
      description:
        "앤트러사이트는 블렌드 커피에 대한 철학과 상상력을 현실화 시키는 특별함이 있어요.",
    },
    products: [
      {
        id: "p21",
        url: "https://product.29cm.co.kr/catalog/1568728",
        image: "img/main_right/p4-1.webp",
        alt: "콜드브루 윌리엄 블레이크 2종",
        brand: "앤트러사이트",
        name: "콜드브루 윌리엄 블레이크 2종",
        price: "15,000",
        likes: "137",
      },
      {
        id: "p22",
        url: "https://product.29cm.co.kr/catalog/1568709",
        image: "img/main_right/p4-2.webp",
        alt: "앤트러사이트 원두 버터 팻 트리오",
        brand: "앤트러사이트",
        name: "앤트러사이트 원두 버터 팻 트리오",
        price: "13,000",
        likes: "1K",
      },
    ],
  },
  {
    id: "c3",
    type: "product",
    collection: {
      title: "틸버 신상 소식",
      description: "우먼패션뷰에 참여한 틸버의 신상을 지금 바로 만나보세요.",
      image: "img/main_right/p5.webp",
      url: "https://content.29cm.co.kr/brand-news/27960",
    },
    products: [
      {
        id: "p31",
        brand: "틸버",
        name: "스트라이프 버튼 업 셔츠_Black",
        image: "img/main_right/p5-1.webp",
        url: "https://product.29cm.co.kr/catalog/2755708",
        price: "82,280",
        discount: "32%",
        likes: "68",
      },
      {
        id: "p32",
        brand: "틸버",
        name: "스트라이프 버튼 업 셔츠_Beige",
        image: "img/main_right/p5-2.webp",
        url: "https://product.29cm.co.kr/catalog/2755707",
        price: "82,280",
        discount: "32%",
        likes: "144",
      },
    ],
  },
  {
    id: "c4",
    type: "product",
    collection: {
      title: "29어퍼스트로피 x 아고 램프",
      description:
        "기분에 따라서 방향을 조절하는 다재다능함을 갖춘 투웨이 조명을 만나보세요.",
      image: "img/main_right/p6.webp",
      url: "https://content.29cm.co.kr/brand-news/29884",
    },
    products: [
      {
        id: "p41",
        brand: "이구어퍼스트로피",
        name: "[선물하기 쿠폰] 29XAGO ampm 포터블램프 3color",
        image: "img/main_right/p6-1.webp",
        url: "https://product.29cm.co.kr/catalog/2874866",
        price: "113,050",
        discount: "5%",
        likes: "4K",
      },
    ],
  },
  {
    id: "c5",
    type: "product",
    collection: {
      title: "완벽함에 더한 실용성",
      description: "하 아카이브의 연말결산 베스트 아이템을 확인해 보세요.",
      image: "img/main_right/p7.webp",
      url: "https://content.29cm.co.kr/brand-news/33453",
    },
    products: [
      {
        id: "p51",
        brand: "하 아카이브",
        name: "[HAH ARCHIVE] ARK BLACK MESSENGER BAG",
        image: "img/main_right/p7-1.webp",
        url: "https://product.29cm.co.kr/catalog/974484",
        price: "59,415",
        discount: "25%",
        likes: "13K",
      },
      {
        id: "p52",
        brand: "하 아카이브",
        name: "2BUCKLE SHOULDER MESSENGER BAG 002 (BLACK/NICKEL)",
        image: "img/main_right/p7-2.webp",
        url: "https://product.29cm.co.kr/catalog/2473219",
        price: "84,150",
        discount: "29%",
        likes: "356",
      },
    ],
  },
  {
    id: "c6",
    type: "product",
    collection: {
      title: "후기가 증명하는 향과 맛",
      description:
        "벙커컴퍼니는 커피의 매력과 향연을 혁신적으로 재구성하여, 커피 문화를 새로운 차원으로 끌어올리고 있습니다.전통적인 커피의 맛과 향을 보존하며 현대적인 스타일과 조화를 구현하고자 합니다.단순히 음료로서의 한계를 넘어선 예술적인 커피 한잔을 만나보세요.",
      image: "img/main_right/p8.webp",
      url: "https://content.29cm.co.kr/brand-news/16726",
    },
    products: [
      {
        id: "p61",
        brand: "벙커컴퍼니",
        name: "BUNKER#Drip Bag 커피 드립백 10g x 7EA [기프트]",
        image: "img/main_right/p8-1.webp",
        url: "https://product.29cm.co.kr/catalog/2356653",
        price: "13,000",
        discount: null,
        likes: "140",
      },
      {
        id: "p62",
        brand: "벙커컴퍼니",
        name: "BUNKER instant coffee 인스턴트 커피 NET WT 60g [기프트]",
        image: "img/main_right/p8-2.webp",
        url: "https://product.29cm.co.kr/catalog/2356655",
        price: "35,000",
        discount: "5%",
        likes: "910",
      },
    ],
  },
  {
    id: "c7",
    type: "product",
    collection: {
      title: "레더 재킷 마지막 혜택",
      description:
        "다가올 봄을 위한 튜드먼트의 레더 재킷, 특별한 혜택을 받을 수 있는 마지막 기회예요.",
      image: "img/main_right/p9.webp",
      url: "https://product.29cm.co.kr/catalog/2451122",
    },
    products: [
      {
        id: "p71",
        brand: "튜드먼트",
        name: "ITALIAN LAMBSKIN LEATHER JACKET BLACK",
        image: "img/main_right/p9-1.webp",
        url: "https://product.29cm.co.kr/catalog/2451122",
        price: "426,645",
        discount: "15%",
        likes: "2K",
      },
    ],
  },
  {
    id: "c8",
    type: "product",
    collection: {
      title: "눈여겨보던 브랜드만",
      description:
        "요즘 떠오르는 브랜드 아유, 포에브, 미치코런던의 봄 아이템을 특별한 혜택으로 만나보세요.",
      image: "img/main_right/p10.webp",
      url: "https://content.29cm.co.kr/highlight/2025/03/10/2nd",
    },
    products: [
      {
        id: "p81",
        brand: "포에브",
        name: "[3차 재입고] Halter Top Layered Cardigan Set [3 COLOR]",
        image: "img/main_right/p10-1.webp",
        url: "https://product.29cm.co.kr/catalog/3067793",
        price: "78,400",
        discount: "30%",
        likes: "445",
      },
      {
        id: "p82",
        brand: "아유",
        name: "SIDE OPEN PLEATS SKIRT, BLACK",
        image: "img/main_right/p10-2.webp",
        url: "https://product.29cm.co.kr/catalog/2650182",
        price: "159,000",
        discount: null,
        likes: "666",
      },
    ],
  },
  {
    id: "c9",
    type: "product",
    collection: {
      title: "한강에서 만나요",
      description: "다가오는 5월 막강한 라인업의 뮤직 페스티벌이 열립니다.",
      image: "img/main_right/p11.webp",
      url: "https://product.29cm.co.kr/catalog/3128998",
    },
    products: [
      {
        id: "p91",
        brand: "피크 페스티벌",
        name: "PEAK FESTIVAL 2025",
        image: "img/main_right/p11-1.webp",
        url: "https://product.29cm.co.kr/catalog/3128998",
        price: "110,000",
        discount: null,
        likes: "677",
      },
    ],
  },
  {
    id: "c10",
    type: "product",
    collection: {
      title: "시각으로 느끼는 독특함",
      description:
        "시각적 표면의 가치를 소비자에게 제안하는 서피스 에디션의 신상품을 만나보세요.",
      image: "img/main_right/p12.webp",
      url: "https://content.29cm.co.kr/brand-news/38359",
    },
    products: [
      {
        id: "p101",
        brand: "서피스에디션",
        name: "NOIR RIDER JACEKT",
        image: "img/main_right/p12-1.webp",
        url: "https://product.29cm.co.kr/catalog/3130401",
        price: "348,000",
        discount: null,
        likes: "12",
      },
      {
        id: "p102",
        brand: "서피스에디션",
        name: "HERRINGBONE TRUCKER JACKET BLACK",
        image: "img/main_right/p12-2.webp",
        url: "https://product.29cm.co.kr/catalog/3130402",
        price: "278,000",
        discount: null,
        likes: "7",
      },
    ],
  },
  {
    id: "c11",
    type: "product",
    collection: {
      title: "일상이 예술이 되는 순간",
      description:
        "세상을 섬세하게 담아낸 워너브롱크 호스트의 전시, 지금 함께하세요.",
      image: "img/main_right/p13.webp",
      url: "https://product.29cm.co.kr/catalog/3136119",
    },
    products: [
      {
        id: "p111",
        brand: "워너 브롱크호스트: 온 세상이 캔버스",
        name: "[3-5월 입장권] 워너 브롱크호스트: 온 세상이 캔버스",
        image: "img/main_right/p13-1.webp",
        url: "https://product.29cm.co.kr/catalog/3136119",
        price: "18,000",
        discount: null,
        likes: "2K",
      },
    ],
  },
  {
    id: "c12",
    type: "product",
    collection: {
      title: "과거와 현재의 스타일 조화",
      description:
        "오가프는 빈티지의 역사와 서브컬처의 본질을 탐구합니다. 빈티지 문화를 전파함과 동시에 이를 현대적인 디자인으로 재해석해 캐주얼한 상품을 제작하고 있습니다. 여러 번의 수정을 거듭한 패턴과 가봉 과정을 거쳐 완벽에 가까운 실루엣을 합리적인 가격으로 선보입니다.",
      image: "img/main_right/p14.webp",
      url: "https://content.29cm.co.kr/brand-news/38913",
    },
    products: [
      {
        id: "p121",
        brand: "오가프",
        name: "VTG Logo 6Panel Cap Yellow",
        image: "img/main_right/p14-1.webp",
        url: "https://product.29cm.co.kr/catalog/3088986",
        price: "49,000",
        discount: null,
        likes: "11",
      },
      {
        id: "p122",
        brand: "오가프",
        name: "VTG Logo 6Panel Cap Red",
        image: "img/main_right/p14-2.webp",
        url: "https://product.29cm.co.kr/catalog/3088985",
        price: "49,000",
        discount: null,
        likes: "93",
      },
    ],
  },
  {
    id: "c13",
    type: "product",
    collection: {
      title: "3월의 무브웜",
      description:
        "움직임을 더 가볍게 도와줄 월간 무브웜 소식을 전해요. 야외활동과 어울리는 데일리웨어만 모아 소개합니다.",
      image: "img/main_right/p15.webp",
      url: "https://content.29cm.co.kr/brand-news/38977",
    },
    products: [
      {
        id: "p131",
        brand: "무브웜",
        name: "Multi Shield Bolero- 2Colors",
        image: "img/main_right/p15-1.webp",
        url: "https://product.29cm.co.kr/catalog/2248622",
        price: "179,000",
        discount: null,
        likes: "793",
      },
      {
        id: "p132",
        brand: "무브웜",
        name: "Trail Pants- 2Colors",
        image: "img/main_right/p15-2.webp",
        url: "https://product.29cm.co.kr/catalog/2850640",
        price: "89,000",
        discount: null,
        likes: "1K",
      },
    ],
  },
  {
    id: "c14",
    type: "product",
    collection: {
      title: "일상의 고유한 조각",
      description:
        "개인의 규칙과 가치를 존중하는 칼리코의 신상을 확인해 보세요.",
      image: "img/main_right/p16.webp",
      url: "https://content.29cm.co.kr/brand-news/33566",
    },
    products: [
      {
        id: "p141",
        brand: "칼리코",
        name: "칼리코 진즈 2.2 (Womens)",
        image: "img/main_right/p16-1.webp",
        url: "https://product.29cm.co.kr/catalog/2986737",
        price: "138,000",
        discount: null,
        likes: "18",
      },
      {
        id: "p142",
        brand: "칼리코",
        name: "칼리코 진즈 2.2 (Mens)",
        image: "img/main_right/p16-2.webp",
        url: "https://product.29cm.co.kr/catalog/2986732",
        price: "149,000",
        discount: null,
        likes: "60",
      },
    ],
  },
  {
    id: "c15",
    type: "product",
    collection: {
      title: "봄날의 식탁 위에서",
      description:
        "프랑스 감성을 담은 르크루제 테이블웨어로 봄의 분위기를 차분하게 더해보세요.",
      image: "img/main_right/p17.webp",
      url: "https://shop.29cm.co.kr/brand/29113",
    },
    products: [
      {
        id: "p151",
        brand: "르크루제",
        name: "로고 파스타볼 25cm_4 Colors",
        image: "img/main_right/p17-1.webp",
        url: "https://product.29cm.co.kr/catalog/2353787",
        price: "40,500",
        discount: "46%",
        likes: "3K",
      },
      {
        id: "p152",
        brand: "르크루제",
        name: "[SET] 프렌치 머그 300ml 2P_5 Colors",
        image: "img/main_right/p17-2.webp",
        url: "https://product.29cm.co.kr/catalog/2995902",
        price: "41,400",
        discount: "52%",
        likes: "1K",
      },
    ],
  },
  {
    id: "c16",
    type: "product",
    collection: {
      title: "행복한 할인 전시",
      description:
        "전시 '우연히 웨스 앤더슨 2'의 연장 기념 할인 소식을 전해요.",
      image: "img/main_right/p18.webp",
      url: "https://product.29cm.co.kr/catalog/3154093",
    },
    products: [
      {
        id: "p161",
        brand: "우연히 웨스 앤더슨 2: 모험은 계속된다",
        name: "[연장 기념 할인] 우연히 웨스 앤더슨 2",
        image: "img/main_right/p18-1.webp",
        url: "https://product.29cm.co.kr/catalog/3154093",
        price: "14,400",
        discount: "20%",
        likes: "643",
      },
    ],
  },
  {
    id: "c17",
    type: "product",
    collection: {
      title: "경계를 초월한 일상",
      description:
        "일상과 아웃도어의 경계를 허문 케일의 아이템은 활동성과 스타일을 모두 갖췄어요.",
      image: "img/main_right/p19.webp",
      url: "https://content.29cm.co.kr/brand-news/39989",
    },
    products: [
      {
        id: "p171",
        brand: "케일",
        name: "BREATHE CAP (Olive Brown)",
        image: "img/main_right/p19-1.webp",
        url: "https://product.29cm.co.kr/catalog/3158628",
        price: "56,000",
        likes: "58",
      },
      {
        id: "p172",
        brand: "케일",
        name: "LIGHT EQ PANTS (Denim Blue)",
        image: "img/main_right/p19-2.webp",
        url: "https://product.29cm.co.kr/catalog/3158627",
        price: "158,000",
        likes: "22",
      },
    ],
  },
  {
    id: "c18",
    type: "product",
    collection: {
      title: "신선함과 자유로움의 조화",
      description:
        "시대적 흐름에 맞게 계속 발전해나가며, 미래로 이어지는 무한한 가능성을 바탕으로 자유롭고 신선한 디자인을 전개하는 브랜드 유체를 만나보세요.",
      image: "img/main_right/p20.webp",
      url: "https://content.29cm.co.kr/brand-news/40061",
    },
    products: [
      {
        id: "p181",
        brand: "유체 프레타 포르테",
        name: "AR TWEED BLOUSON JACKET Black",
        image: "img/main_right/p20-1.webp",
        url: "https://product.29cm.co.kr/catalog/2860655",
        price: "328,000",
        likes: "9",
      },
      {
        id: "p182",
        brand: "유체 프레타 포르테",
        name: "AR OBLIQUE ALPACA KNIT Black",
        image: "img/main_right/p20-2.webp",
        url: "https://product.29cm.co.kr/catalog/2860653",
        price: "185,000",
        likes: "5",
      },
    ],
  },
  {
    id: "c19",
    type: "product",
    collection: {
      title: "하루종일 시원하게",
      description:
        "언제 어디서나 함께 하는 스탠리. 감각적인 컬러로 수분 가득한 일상을 즐기세요.",
      image: "img/main_right/p21.webp",
      url: "https://shop.29cm.co.kr/brand/30351",
    },
    products: [
      {
        id: "p191",
        brand: "스탠리",
        name: "[스탠리공식유통사] 퀜처 H2.0 플로우스테이트 텀블러 887ml",
        image: "img/main_right/p21-1.webp",
        url: "https://product.29cm.co.kr/catalog/2364755",
        price: "49,000",
        likes: "36K",
      },
      {
        id: "p192",
        brand: "스탠리",
        name: "[스탠리공식유통사] 카페 투 고 트래블 머그",
        image: "img/main_right/p21-2.webp",
        url: "https://product.29cm.co.kr/catalog/3184277",
        price: "35,000",
        likes: "1K",
      },
    ],
  },
  {
    id: "c20",
    type: "product",
    collection: {
      title: "테일러드 브라핏의 완벽함",
      description:
        "테일러드 브라핏 가이드를 캘빈클라인 언더웨어에서 만나보세요",
      image: "img/main_right/p22.webp",
      url: "https://content.29cm.co.kr/brand-news/40411",
    },
    products: [
      {
        id: "p201",
        brand: "캘빈클라인 언더웨어",
        name: "여성 퍼펙틀리 핏 소프트 와이어 티셔츠 브라 세트(5 Color)",
        image: "img/main_right/p22-1.webp",
        url: "https://product.29cm.co.kr/catalog/3206947",
        price: "179,000",
        likes: "20",
      },
      {
        id: "p202",
        brand: "캘빈클라인 언더웨어",
        name: "여성 퍼펙틀리 핏 소프트 와이어 티셔츠 브라_F3837AD001",
        image: "img/main_right/p22-2.webp",
        url: "https://product.29cm.co.kr/catalog/3012904",
        price: "116,000",
        discount: "10%",
        likes: "12",
      },
    ],
  },
  {
    id: "c21",
    type: "product",
    collection: {
      title: "독창적인 표현",
      description:
        "독창적인 표현기법과 색채, 소재를 통해 옷으로써 구체화 하는 예스아이씨를 단독 혜택으로 만나보세요.",
      image: "img/main_right/p23.webp",
      url: "https://content.29cm.co.kr/brand-news/40449",
    },
    products: [
      {
        id: "p211",
        brand: "예스아이씨",
        name: "Racing 22 Tee White",
        image: "img/main_right/p23-1.webp",
        url: "https://product.29cm.co.kr/catalog/2519549",
        price: "33,750",
        discount: "25%",
        likes: "206",
      },
      {
        id: "p212",
        brand: "예스아이씨",
        name: "Racing 22 Tee Black",
        image: "img/main_right/p23-2.webp",
        url: "https://product.29cm.co.kr/catalog/2519548",
        price: "33,750",
        discount: "25%",
        likes: "253",
      },
    ],
  },
  {
    id: "c22",
    type: "product",
    collection: {
      title: "디테일로 완성되는 룩",
      description:
        "차분한 컬러 속 독특한 디테일의 조화를 통해 일상 속 멋스러운 스타일링을 완성해요.",
      image: "img/main_right/p24.webp",
      url: "https://content.29cm.co.kr/showcase/2453",
    },
    products: [
      {
        id: "p221",
        brand: "락케이크",
        name: "Curve Line Essential Top - 7 Colors",
        image: "img/main_right/p24-1.webp",
        url: "https://product.29cm.co.kr/catalog/3196051",
        price: "33,150",
        discount: "15%",
        likes: "223",
      },
      {
        id: "p222",
        brand: "락케이크",
        name: "Eyelet R Pocket Curved Pants - White",
        image: "img/main_right/p24-2.webp",
        url: "https://product.29cm.co.kr/catalog/3179003",
        price: "90,300",
        discount: "30%",
        likes: "54",
      },
    ],
  },
  {
    id: "c23",
    type: "product",
    collection: {
      title: "기억에 남는 선물",
      description:
        "더 그란의 이번 컬렉션은 사랑하는 사람을 만나러 가는 순간의 설레는 감정을 담았습니다.",
      image: "img/main_right/p25.webp",
      url: "https://content.29cm.co.kr/showcase/2444",
    },
    products: [
      {
        id: "p231",
        brand: "더 그란",
        name: "[선물포장] 페이스 타월 3P기획 모음전 - 블러쉬 핑크 스트라이프, 블루 포그, 블루 핑크 스퀘어 (에디션_러브컬렉션) 기프트세트 쇼핑백별도구매",
        image: "img/main_right/p25-1.webp",
        url: "https://product.29cm.co.kr/catalog/3185839",
        price: "53,452",
        discount: "12%",
        likes: "666",
      },
      {
        id: "p232",
        brand: "더 그란",
        name: "[선물포장] 더 그란 2P 기프트 세트 - [에디션] 페이스 타월 / 블러쉬핑크스트라이프, 블루포그, 블루핑크스퀘어_러브컬렉션 (2 Options) 기프트세트 쇼핑백별도구매",
        image: "img/main_right/p25-2.webp",
        url: "https://product.29cm.co.kr/catalog/3195179",
        price: "35,782",
        discount: "12%",
        likes: "1K",
      },
    ],
  },
  {
    id: "c24",
    type: "product",
    collection: {
      title: "끝나지 않을 대화",
      description: "피크닉, 새로운 전시",
      image: "img/main_right/p26.webp",
      url: "https://product.29cm.co.kr/catalog/3190546",
    },
    products: [
      {
        id: "p241",
        brand: "피크닉",
        name: "끝나지 않을 대화 CORRESPONDENCES",
        image: "img/main_right/p26-1.webp",
        url: "https://product.29cm.co.kr/catalog/3190546",
        price: "10,000",
        discount: null,
        likes: "176",
      },
    ],
  },
  {
    id: "c25",
    type: "product",
    collection: {
      title: "4월의 무브웜",
      description:
        "무브웜과 함께 다시 몸을 일으켜요. 움직임의 시작을 응원할 5% 혜택을 놓치지마세요.",
      image: "img/main_right/p27.webp",
      url: "https://content.29cm.co.kr/brand-news/40823",
    },
    products: [
      {
        id: "p251",
        brand: "무브웜",
        name: "Breezy Hoodie- 4Colors",
        image: "img/main_right/p27-1.webp",
        url: "https://product.29cm.co.kr/catalog/2420135",
        price: "79,000",
        discount: null,
        likes: "4K",
      },
      {
        id: "p252",
        brand: "무브웜",
        name: "Soft Crop Top- 4Colors",
        image: "img/main_right/p27-2.webp",
        url: "https://product.29cm.co.kr/catalog/2067966",
        price: "56,000",
        discount: null,
        likes: "1K",
      },
    ],
  },
  {
    id: "c26",
    type: "product",
    collection: {
      title: "내 거 하기 딱 좋은 타이밍",
      description: "Apple Watch 역사에 한 획을 긋는 Series 10",
      image: "img/main_right/p28.webp",
      url: "https://content.29cm.co.kr/brand-news/33888",
    },
    products: [
      {
        id: "p261",
        brand: "Apple",
        name: "애플워치 10 GPS 42mm 실버 알루미늄, 데님 스포츠 밴드 (S/M) MWWA3KH/A",
        image: "img/main_right/p28-1.webp",
        url: "https://product.29cm.co.kr/catalog/2798701",
        price: "499,000",
        discount: "17%",
        likes: "153",
      },
    ],
  },
  {
    id: "c27",
    type: "product",
    collection: {
      title: "오랜 이야기 담긴 빈티지",
      description:
        "오랜 시간 빈티지 의류를 사랑해온 디렉터의 감성과, 그간 복각 브랜드를 운영하며 쌓아온 노하우. 여기에 어린 시절부터 미디어와 책을 통해 키워온 상상력이 더해져 탄생한 브랜드, The Geeks를 만나보세요.",
      image: "img/main_right/p29.webp",
      url: "https://content.29cm.co.kr/brand-news/41113",
    },
    products: [
      {
        id: "p271",
        brand: "더 긱스",
        name: "Pestilence tour T-shirt - White",
        image: "img/main_right/p29-1.webp",
        url: "https://product.29cm.co.kr/catalog/3232480",
        price: "129,000",
        discount: null,
        likes: "0",
      },
      {
        id: "p272",
        brand: "더 긱스",
        name: "Pestilence tour T-shirt - Black",
        image: "img/main_right/p29-2.webp",
        url: "https://product.29cm.co.kr/catalog/3232477",
        price: "129,000",
        discount: null,
        likes: "0",
      },
    ],
  },
  {
    id: "c28",
    type: "product",
    collection: {
      title: "사랑스러운 향기",
      description:
        "깔루 파퓸스의 귀엽고 사랑스러운 향을 특별한 헤택과 함께 만나보세요.",
      image: "img/main_right/p30.webp",
      url: "https://content.29cm.co.kr/focus/2025/04/21/kaloo?cache=true",
    },
    products: [
      {
        id: "p281",
        brand: "깔루 파퓸스",
        name: "블루 EDS 95ML+곰인형 세트",
        image: "img/main_right/p30-1.webp",
        url: "https://product.29cm.co.kr/catalog/3064533",
        price: "62,100",
        discount: "10%",
        likes: "28",
      },
      {
        id: "p282",
        brand: "깔루 파퓸스",
        name: "릴리로즈 EDS 95ML+곰인형 세트",
        image: "img/main_right/p30-2.webp",
        url: "https://product.29cm.co.kr/catalog/3064535",
        price: "62,100",
        discount: "10%",
        likes: "39",
      },
    ],
  },
  {
    id: "c29",
    type: "product",
    collection: {
      title: "트렌디 빈티지의 묘미",
      description:
        "서지웨어는 최고의 품질을 지향하며 빈티지 스포츠 웨어를 기반으로 만들어지는 브랜드 입니다. 빈티지와 같은 만듦새에 트렌디한 실루엣을 가미하여 합리적인 가격대에 누구나 입을 수 있는 라인업을 선 보이고 있습니다.",
      image: "img/main_right/p31.webp",
      url: "https://content.29cm.co.kr/brand-news/39607",
    },
    products: [
      {
        id: "p291",
        brand: "서지웨어",
        name: "Standard Sweat shirt - Black",
        image: "img/main_right/p31-1.webp",
        url: "https://product.29cm.co.kr/catalog/3123313",
        price: "149,000",
        discount: null,
        likes: "12",
      },
      {
        id: "p292",
        brand: "서지웨어",
        name: "Standard Sweat shirt - Navy",
        image: "img/main_right/p31-2.webp",
        url: "https://product.29cm.co.kr/catalog/3123307",
        price: "149,000",
        discount: null,
        likes: "14",
      },
    ],
  },
  {
    id: "c30",
    type: "product",
    collection: {
      title: "과거와 현재의 조화",
      description:
        "유행을 좇지 않고 과거로부터 이어져 온 것들을 현재에 반영합니다. 셔터와 함께 변함없는 가치를 느껴보세요.",
      image: "img/main_right/p32.webp",
      url: "https://content.29cm.co.kr/brand-news/40059",
    },
    products: [
      {
        id: "p301",
        brand: "셔터",
        name: "EDITOR SHIRT (PIN BLUE)",
        image: "img/main_right/p32-1.webp",
        url: "https://product.29cm.co.kr/catalog/3182971",
        price: "178,000",
        discount: null,
        likes: "11",
      },
      {
        id: "p302",
        brand: "셔터",
        name: "EDITOR SHIRT (PIN WHITE)",
        image: "img/main_right/p32-2.webp",
        url: "https://product.29cm.co.kr/catalog/3182969",
        price: "178,000",
        discount: null,
        likes: "10",
      },
    ],
  },
  {
    id: "c31",
    type: "product",
    collection: {
      title: "별밤이 추천하는 썸머 데일리 아이템",
      description:
        "인플루언서 별밤님이 소개하는 플랙 우먼의 SUMMER 컬렉션 발매 소식을 전할게요. 그녀의 감성을 더한 썸머 스타일링을 지금 바로 만나보세요.",
      image: "img/main_right/p33.webp",
      url: "https://content.29cm.co.kr/brand-news/41098",
    },
    products: [
      {
        id: "p311",
        brand: "플랙",
        name: "U넥 버튼 슬리브리스 탑_3colors",
        image: "img/main_right/p33-1.webp",
        url: "https://product.29cm.co.kr/catalog/3209094",
        price: "42,777",
        discount: "13%",
        likes: "99",
      },
      {
        id: "p312",
        brand: "플랙",
        name: "리틀 플라워 셔링 블라우스_3colors",
        image: "img/main_right/p33-2.webp",
        url: "https://product.29cm.co.kr/catalog/3209083",
        price: "77,697",
        discount: "13%",
        likes: "319",
      },
    ],
  },
  {
    id: "c32",
    type: "product",
    collection: {
      title: "책상 위 특별한 동반자",
      description: "레토의 추천아이템을 만나보세요.",
      image: "img/main_right/p34.webp",
      url: "https://content.29cm.co.kr/brand-news/41242",
    },
    products: [
      {
        id: "p321",
        brand: "레토",
        name: "레토 무선 탁상용 선풍기 자동 회전 미니 소형 캠핑 책상 사무실 10단풍량",
        image: "img/main_right/p34-1.webp",
        url: "https://product.29cm.co.kr/catalog/3233499",
        price: "25,900",
        discount: "35%",
        likes: "60",
      },
      {
        id: "p322",
        brand: "레토",
        name: "휴대용 무선 선풍기 높이조절 무드등 겸용 LMF-PS01",
        image: "img/main_right/p34-2.webp",
        url: "https://product.29cm.co.kr/catalog/1503718",
        price: "25,900",
        discount: "35%",
        likes: "303",
      },
    ],
  },
  {
    id: "c33",
    type: "product",
    collection: {
      title: "마음을 전해드려요",
      description:
        "소중한 마음을 전해줄 웜그레이테일의 봄 신상품을 소개합니다.",
      image: "img/main_right/p35.webp",
      url: "https://content.29cm.co.kr/brand-news/41104",
    },
    products: [
      {
        id: "p331",
        brand: "웜그레이테일",
        name: "[29CM 단독] 수(사자)세미 2P 세트",
        image: "img/main_right/p35-1.webp",
        url: "https://product.29cm.co.kr/catalog/3224507",
        price: "9,500",
        discount: "5%",
        likes: "2K",
      },
      {
        id: "p332",
        brand: "웜그레이테일",
        name: "플러피 독 법랑 플레이트 - 웜그레이",
        image: "img/main_right/p35-2.webp",
        url: "https://product.29cm.co.kr/catalog/3222529",
        price: "30,600",
        discount: "10%",
        likes: "126",
      },
    ],
  },
  {
    id: "c34",
    type: "product",
    collection: {
      title: "비가 반가워지는 순간",
      description: "우산, 장화 등 비 오는 날 유용한 상품을 모아 소개해요.",
      image: "img/main_right/p36.webp",
      url: "https://content.29cm.co.kr/collection/11983",
    },
    products: [
      {
        id: "p341",
        brand: "지비에이치",
        name: "3-FOLDING UMBRELLA 자동3단우산 자외선차단우양산",
        image: "img/main_right/p36-1.webp",
        url: "https://product.29cm.co.kr/catalog/1196477",
        price: "41,000",
        discount: null,
        likes: "23K",
      },
      {
        id: "p342",
        brand: "포유렐라",
        name: "포유렐라 벚꽃 튼튼한 투명 돔형 장우산 자동 우산",
        image: "img/main_right/p36-2.webp",
        url: "https://product.29cm.co.kr/catalog/3220850",
        price: "8,900",
        discount: "41%",
        likes: "165",
      },
    ],
  },
];

export default data;
